### ISSUE TITLE
dockerhub readme out of sync with repositorie's.

### ISSUE THREAD

**Issue by Jviguy** [pmmp/PocketMine-Docker#14]
As of now when visiting the https://hub.docker.com/r/pmmp/pocketmine-mp theres a simple difference in the file displayed there and from here. Thus that when trying to use the docker hub link you will find your self with a tcp docker proxy port rather than a udp. This is fixed in the current read me found in this repo by using udp port mapping. It just needs to be updated on the docker hub.

**Comment by SOF3** [comment]
Updated.
