### ISSUE TITLE
PocketMine-MP version

### ISSUE THREAD

**Issue by zkita** [pmmp/PocketMine-Docker#19]
How can I change the version of pocketmine, I can't find the folder called `/pocketmine` directly

**Comment by SOF3** [comment]
I don't understand what you want to do. Are you trying to update PocketMine?
Each docker image corresponds to one version of PocketMine. You need to use another image tag if you want to update. Alternatively, if you use the `latest` tag, you need to `docker pull pmmp/pocketmine-mp`.
