### ISSUE TITLE
gmplib.org blocked GitHub Actions, breaking all builds

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-Docker#24]
https://github.com/pmmp/PocketMine-MP/actions/runs/5430769569

compile.sh recently started using SSL for all downloaded packages. This worked fine for the regular PHP builds, but appears to have caused problems for the Docker image build.

This is likely because the Docker image is still built on the obsolete Ubuntu 18.04, and the `ca-certificates` package is therefore outdated.

**Comment by dktapps** [comment]
Turns out this has nothing to do with SSL, and everything to do with gmplib.org IP range-banning the entire of Microsoft due to GitHub Actions spamming their download server.

We'll need a mirror to fix this problem. I've been intending to setup a PMMP mirror for some time due to random outages of various library downloads anyway.

**Comment by NatKarmios** [comment]
Oh that's fun, our builds were broken by this too. Thanks for spreading the word!

**Comment by dktapps** [comment]
Thanks for bumping the issue, I'd forgotten to close it. For now we're mirroring select packages to https://github.com/pmmp/DependencyMirror/releases
